language: node_js
node_js:
  - 12

before_script:
  - npm install
  - npm run build

script:
  - npm run lint
  - npm run test

after_success:
  - npm run docs

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "wsl-http-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "wisedataintegration@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true